/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaohan_ffmpegdecoder_FFmepegDecoder */

#ifndef _Included_com_xiaohan_ffmpegdecoder_FFmepegDecoder
#define _Included_com_xiaohan_ffmpegdecoder_FFmepegDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaohan_ffmpegdecoder_FFmepegDecoder
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaohan_ffmpegdecoder_FFmepegDecoder_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
